name: quizon
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Firebase (required)
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  firebase_core_web: 2.24.1
  
  # Other Firebase services (add as needed)
  cloud_firestore: ^5.6.11
  
  # State management
  provider: ^6.1.1
  
  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true